version: '2.1'
services:

  localstack:
    image: localstack/localstack-full
    ports:
      - "4572:4572"
      - "8080:8080"
      - "4566:4566"
      - "4571:4571"
      - "4576:4576"
    environment:
      - SERVICES=s3,sqs
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: .
    volumes:
        - .:/src
        - nodemodules:/src/node_modules
    restart: on-failure
    # command: npm test
    ports:
        - "3000:3000"
    links:
        - localstack
    depends_on: 
        - localstack
    environment: 
        LOCALSTACK_HOST: localstack
        S3_PORT: 4566
        SQS_PORT: 4566

volumes:
    nodemodules: {}